# *************************************************************************
#                 Implementation of phase-field model of ductile fracture
#                      Upadhyayula Sai Viswanadha Sastry
#                         Personal Programming Project
#                               65130
# *************************************************************************
"""
This file is used to plot deformation of a problem and contour plots of displacement
by using json file which has data generated by executing the program.
"""
import json
from input_abaqus import input_parameters
from plots import plot_deformation_with_nodes,plot_displacement_contour

# input file name can be changed based on the data needed to be extracted
with open("data_shear.json", "r") as opf:    
    disp = json.load(opf)

# load type 0 for tensile and 1 for shear
load_type = 1

# problem 0 for elastic and 1 for elastic-plastic brittle fracture
problem = 0
Displacement = disp['0.001']

# separating displacement in x and y directions
X_disp = Displacement[0:len(Displacement):2]
Y_disp = Displacement[1:len(Displacement):2]

# Call inputs
inputs = input_parameters(load_type,problem)
num_dim, num_node_elem, nodes, num_node, elements, num_elem, num_dof, num_Gauss, num_stress = inputs.geometry_parameters()

plot_deformation_with_nodes(nodes,X_disp,Y_disp)
plot_displacement_contour(nodes,Y_disp,0.001)
